name: BMS Scraper

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'scrapper.js'
      - 'package.json'
      - '.github/workflows/scraper.yml'

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Prevent hanging jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --only=production
        npx playwright install chromium --with-deps
        
    - name: Run scraper
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        BMS_USERNAME: ${{ secrets.BMS_USERNAME }}
        BMS_PASSWORD: ${{ secrets.BMS_PASSWORD }}
      run: |
        echo "🚀 Starting BMS scraper at $(date)"
        timeout 300 node scrapper-optimized.js || echo "⚠️ Scraper timed out after 5 minutes"
        echo "✅ Scraper completed at $(date)"
        
    - name: Upload debug files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-files-${{ github.run_number }}
        path: |
          debug-*.html
          debug-*.png
        retention-days: 7
