name: BMS Scraper - Every 30 Minutes

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Fail if scraper takes more than 15 minutes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Install dependencies
        run: npm ci

      - name: Run BMS scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          BMS_USERNAME: ${{ secrets.BMS_USERNAME }}
          BMS_PASSWORD: ${{ secrets.BMS_PASSWORD }}
        run: node scrapper.js

      - name: Upload debug files (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files-${{ github.run_number }}
          path: |
            debug-*.html
            debug-*.png
          retention-days: 7

